### ISSUE TITLE
Make Input fields as required

### ISSUE THREAD

**Issue by sourabhtk37** [rmenn/atm-dispensing#6]
I see some people just fill a single field and leave the rest blank. It would be better if the HTML input fields be "required" and respective error handling to be created. :)

**Comment by arasu-rrk** [comment]
@sourabhtk37 I've already sent PR for this. But admin not yet approved...

https://github.com/rmenn/atm-dispensing/pull/4

**Comment by rmenn** [comment]
This has been merged and deployed
